name: Release iRODS Rule Async Exec Cmd
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm, arm64]
    env:
      PKG: "github.com/cyverse/irods-rule-async-exec-cmd"
    steps:
    - name: "set build date"
      run: echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.31
      with:
        github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        goversion: 1.18
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./client-cmd/"
        binary_name: "irods-rule-async-exec-cmd"
        ldflags: "-X ${{ env.PKG }}/commons.releaseVersion=${{ github.ref_name }} -X ${{ env.PKG }}/commons.gitCommit=${{ github.sha }} -X ${{ env.PKG }}/commons.buildDate=${{ env.BUILD_DATE }}"
    - uses: wangyoucao577/go-release-action@v1.31
      with:
        github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        goversion: 1.18
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./server-cmd/"
        binary_name: "irods-rule-async-exec-cmd-svc"
        ldflags: "-X ${{ env.PKG }}/commons.releaseVersion=${{ github.ref_name }} -X ${{ env.PKG }}/commons.gitCommit=${{ github.sha }} -X ${{ env.PKG }}/commons.buildDate=${{ env.BUILD_DATE }}"
